# Generated by Django 5.1 on 2024-08-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_for_speed_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='need_for_speed_app.user')),
                ('company_name', models.CharField(max_length=255)),
                ('number_of_workers', models.IntegerField()),
            ],
            bases=('need_for_speed_app.user',),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='license',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='worklocation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='need_for_speed_app.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivering_order', to='need_for_speed_app.delivery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_from_company', to='need_for_speed_app.company'),
        ),
    ]
