# Generated by Django 5.1 on 2024-08-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_for_speed_app', '0002_company_customer_status_delivery_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
